spring.application.name=shitu-admin-web

server.port= 8081
server.servlet.context-path= /
server.servlet.session.timeout= 30m

spring.thymeleaf.cache= false
spring.thymeleaf.prefix= classpath:/templates/
spring.thymeleaf.suffix= .html
spring.thymeleaf.mode= HTML
spring.thymeleaf.encoding= UTF-8

spring.web.resources.static-locations= classpath:/static/
spring.web.resources.cache.period=0

api.base-url= http://localhost:8080/api/v1