spring.application.name=shitu-api


server.port=8080
server.servlet.context-path=/


spring.datasource.url=jdbc:mysql://localhost:3306/shitu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=l3588563945
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never
spring.sql.init.schema-locations= classpath:schema.sql  
spring.sql.init.data-locations= classpath:data.sql     

# Hikari
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.serialization.write-dates-as-timestamps=false

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.liang.shituapi.entity
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl


# JWT
jwt.secret=shitu-secret-key-2024
jwt.expiration=86400000
jwt.header=Authorization


logging.level.com.shitu=debug
logging.level.org.springframework=warn


# ??????
amap.key=8d068dd7a35a0d38704ed6443e7953c2
amap.geocode-url= https://restapi.amap.com/v3/geocode/geo
amap.static-map-url= https://restapi.amap.com/v3/staticmap
amap.static-map-daily-limit= 10000
amap.geocode-daily-limit= 10000
amap.warning-threshold= 80


